[package]
name = "citron-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "^0.9"
serde = { version = "^1.0", optional = true, features = ["derive"] }
rayon = { version = "^1.10", optional = true }

ndarray = { version = "^0.15", optional = true }
tensorflow = { version = "^0.21", optional = true, features = ["ndarray"]}

[dev-dependencies]
criterion = "^0.3"

[features]
default = ["nn_evaluation"]
debug = []
nn_evaluation = ["ndarray", "tensorflow", "rayon"]
serde = ["dep:serde"]

[[bench]]
name = "simple_position"
harness = false
