[package]
name = "citron-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "^0.9"
tch = { version = "^0.7", optional = true }
serde = { version = "^1.0", optional = true, features = ["derive"] }

[dev-dependencies]
criterion = "^0.3"

[features]
debug = []
nn_evaluation = ["tch"]
serde = ["dep:serde"]

[[bench]]
name = "simple_position"
harness = false
