[package]
name = "chesty-core"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "*"
rayon = "^1.5"
dashmap = "^5.0"

[dev-dependencies]
criterion = "^0.3"

[features]
debug = []

[[bench]]
name = "simple_position"
harness = false
